import { test, expect } from '@playwright/test';

test.describe('AI Generated Fanvue Test', () => {
  test('Test generated by Claude AI to demonstrate the integration of AI-powered test generation with Playwright', async ({ page }) => {
    // Step 1: Navigate to https://www.fanvue.com/
    await page.goto('https://www.fanvue.com/');
    
    // Step 2: Accept cookies if present
    try {
      await page.getByRole('link', { name: 'OK', exact: true }).click({ timeout: 5000 });
    } catch (e) {
      // Cookie banner might not be visible
    }
    
    // Step 3: Verify the main heading is visible
    const mainHeading = page.locator('h1').first();
    await expect(mainHeading).toBeVisible();
    await expect(mainHeading).toContainText('Platform');
    
    // Ensure we're in desktop view for navigation visibility
    await page.setViewportSize({ width: 1280, height: 720 });
    
    // Step 4: Click on 'fanvue AI' in navigation
    await page.getByRole('link', { name: 'fanvue AI' }).click();
    
    // Step 5: Verify navigation to AI page
    await expect(page).toHaveURL(/.*fanvue-ai/);
    await expect(page).toHaveTitle(/.*AI/);
    const aiHeading = page.locator('h1:has-text("The only AI subscription platform")');
    await expect(aiHeading).toBeVisible();
    
    // Step 6: Go back to homepage
    await page.goBack();
    await expect(page).toHaveURL('https://www.fanvue.com/');
    
    // Step 7: Click on 'Our Mission' in navigation
    await page.getByRole('link', { name: 'Our Mission' }).click();
    
    // Step 8: Verify navigation to mission page
    await expect(page).toHaveURL(/.*notion.*|.*mission/);
    await expect(page).toHaveTitle(/.*Mission|.*Values/);
  });
});